### PR TITLE
Macros of!, empty! and from_iter! replaced by functions.

### PR DESCRIPTION
**Pull request by achary**
I'm proposing a change that (partially) addresses #23 and replaces macros with plain strongly typed and constrained functions.
Hope you'll find it useful for further development.

### CODE REVIEW

**Comment by achary** [comment]
BTW: I've noticed pre-0.3 version had functions instead of macros.
I consider #23 as really reasonable and I opt for, wherever possible, adhering to a regular language syntax.
 Was there a particular reason to migrate to macros?

**Comment by M-Adoo** [comment]
There is no particular reason to migrate to macros. Before 0.3, I am still not find a way to not pay cost for multi-thread when the code only run in local thread. During this time, I'm trying to resolve it , not limit every thing must be support shared between thread, so trait and api change frequently. Use macro reduce many work. 

> adhering to a regular language syntax

I'm totally agree with this and very happy to accept this pr. Thank you very much for your work.

There is two little work to do:
1. please update `Unreleased`  in `CHANGELOG.md`
2. remove the `#![allow(unused_imports)]` line after removed macros.

**Comment by achary** [comment]
thanks,
sure, no prob. here is a cleaned up one.

**Comment by achary** [comment]
BTW: Thanks for picking this rx challenge!
I was many times looking for a Rust getting it done. You've managed to move further than any one before (at least in part of web I could search trough).
I'm quite excited seeing Rx in Rust being a real thing, Thanks to your efforts this is becoming a fact. Your library is nicely positioned to be the one (and only). Keep it up!

**Comment by M-Adoo** [comment]
thanks, done.

**Pull request merged**
